### ISSUE TITLE
Apparently arbitrary scaling axis on single-parameter call to setScale()

### ISSUE THREAD

**Issue by theyoyojo** [isenseDev/MYR#110]
So anyway, I've got this duck and its beak is just in awful condition. Really, just terrible. https://learnmyr.org/o8UTFYHcTnSxjicpaLjO

![Selection_012](https://user-images.githubusercontent.com/1909841/54331606-13046200-45f1-11e9-8fd0-e2e15aacfd72.png)

Well, first I know that I want to make it smaller, so I think I'll use that function... hmm... what was it again... Oh yes, setScale()! I think it takes an number, so I'll put in half. That will scale down the beak by a factor of 0.5, right? 

![Selection_014](https://user-images.githubusercontent.com/1909841/54331663-519a1c80-45f1-11e9-87cb-8a5d2c13a987.png)

Wait, what the f- It's only squashed along one axis! Screw this, I'm going to go join the chess club instead of wasting my time with this nerd stuff.

**Comment by theyoyojo** [comment]
Duck update: Duck 1.0 is GA as of 5 seconds ago. Yeah I know it doesn't actually look like a beak, I don't care, I'm going to sleep. https://learnmyr.org/Zy4boEkrTWIxoGpVmvAt

**Comment by theyoyojo** [comment]
I'll Yoss the Sauce for reference:

```
/**********************************************************
*                   Welcome to MYR!                       *
*  Getting Started? - https://learnmyr.org/first-time     *
**********************************************************/

// The main duck
setColor("yellow")
sphere()

// Duck header
setPosition(0,1,1)
setScale(0.5,0.5,0.5)
sphere()

// 2x seeing holes
setScale(0.1,0.1,0.1)
setColor("black")

setPosition(0.3,1.2,1.4)
sphere()

setPosition(-0.3,1.2,1.4)
sphere()

// Eating/General duck-related I/O

setColor("orange")
setScale(0.5,0.5)
setPosition(0,1,1)
tetrahedron()

**Comment by jasondkiesling** [comment]
This is not arbitrary. It set the scale only only the x-axis because that is all that you changed. If you want to set the scale for the x, y, and z axes, then you need to pass through 3 parameters. This is clearly defined in the reference.

**Comment by theyoyojo** [comment]
Yes, I'm aware that it's clearly defined. My point is that it might be confusing to potential users.

**Comment by jasondkiesling** [comment]
I personally see it as a perfect learning opportunity. It teaches them to understand how to read documentation. They think the function does one thing and it looks weird. It is visibly skewed where only one axis got scaled. The user sees the line of code that they wrote and sees that the output does not match their vision. This leads them to think about what the line of code does. If they look in the documentation, they'll see that it requires an x, y, and z parameter to work. We want students to learn how to read documentation and use it to understand how to use the API to make their code work.

Another is that we have set a rule about never breaking existing projects. No matter what changes we make we will either give them a way of upgrading their projects to work with the new API or make it work with both versions. I've done this on purpose before to change only the x or only the x and y scale.

A third issue I see is that it could be confusing to the students to have functions that do different things based off how many parameters you give the function. Right now every function does one thing and one thing only. You can skip later arguments that are set automatically, but they still do one thing. This would be the one function that would break that rule. We would have `setScale(all)` and `setScale(x,y,z)`. I would see that as more confusing to a student.

Our goal is to be clear, but also to provide a challenge. If we simplify things too much, it makes it hard for MYR to be a tool to move on from as you then jump on and add lots of new challenges for the users to face. I think that it really allows a learning opportunity to the user which is what we're looking for. I was not there when you wrote your code and saw the results not look how you wanted it to. However, I can assume that you saw that the output was wrong and wanted to fix it. I assume you opened the reference or an example project and looked at how it was done there. Then you went back to your code to fix it. This is the process that I see us wanting as that is the most valuable skill I see in coding. I see a lot of students in college not understanding documentation and how to read it, and believe that starting early with simple documentation provides a great value to the student.

**Comment by theyoyojo** [comment]
That's a pretty through analysis. I don't have any objections to any of it and I agree with you.

**Comment by theyoyojo** [comment]
Actually, I appreciate the time you spent writing that out in so much detail. Thank you.

**Comment by theyoyojo** [comment]
And yes, that is exactly the process I went through in my head. Did you like the whiney student role-playing?
