### ISSUE TITLE
Sample Scene Unset

### ISSUE THREAD

**Issue by CBernsCode** [isenseDev/MYR#115]
@waltdisgrace Reported that her scene was missing from the sample scenes.

When I checked in the db, it was still there but its UID was unset. 

URL: https://learnmyr.org/YG6MZsWrUPOhIAyFUf2C

**Comment by CBernsCode** [comment]
Not entirely sure what we could do to reproduce but I wanted it tracked in case this is not a one-off.

**Comment by jasondkiesling** [comment]
I'm not sure what happened here. It appears to have been a one off for now. I'm going to close this issue for now and we'll reopen it if we see further issues.
